### ISSUE TITLE
ModuleNotFoundError: No module named 'training.dreambooth'

### ISSUE THREAD

**Issue by petergerten** [satyajitghana/sdxl-dreambooth-finetune#1]
trying to start the script I get:

```
Traceback (most recent call last):
  File "/code/sdxl-dreambooth-finetune/main.py", line 9, in <module>
    from training.dreambooth import train as train_dreambooth
ModuleNotFoundError: No module named 'training.dreambooth'

```

**Comment by satyajitghana** [comment]
Could it be python version issue? I've tested on `3.9.12`

**Comment by satyajitghana** [comment]
One way to fix that would be to convert this into a python library, and do something like `pip install -e .` but i have not set it up yet

**Comment by petergerten** [comment]
thx - I moved the dreambooth file one directory up and imported it from there.
